name: WhosOnWhen
main: io.github.bucksnort2.WhosOnWhen.WhosOnWhen
version: 0.0.1
author: bucksnort2
commands:
  whoson:
    description: Prints out a list of who was on when, how long they were on, and what commands they ran.
    usage: /whoson
    permission: WhosOnWhen.basic
    permission-message: You don't have <permission>